### Site info:
title: Coding Life
tagline: 
author: Wang Zhe
email: wangzhetju@gmail.com
description: "Programming, structures and life." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "c++, algorithm, structures, python"
baseurl: #"/blog" # the subpath of your site, e.g. /blog
url: "http://wangzhe3224.github.io/" # the base hostname & protocol for your site
locale: en_US
google_analytics: UA-66629043-2
comments: true

### Personal info and site tools info:
twitter_username: #wangzhe3224
github_username:  wangzhe3224
disqus_shortname: wangzhe3224
favicon:     "/images/Linux.png"
aboutme: Coding life. # these are shown on aboutme-sidebar.
aboutme_photo: /images/myphoto.png # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: wangzhe3224
      href: http://wangzhetju.wix.com/wangzhe
      title: My blog


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 8
